import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateIncidentReport = (incident, website, remediation) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(8, 8, 10);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(0, 240, 154);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('UPGUARD', 20, 25);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('AI-POWERED INCIDENT REPORT', 20, 32);
  
  // Content Start
  let y = 50;
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text('Incident Overview', 20, y);
  y += 10;
  
  const overviewData = [
    ['Website URL', website.url],
    ['Incident ID', `#${incident.id.slice(-8).toUpperCase()}`],
    ['Detected At', new Date(incident.started_at).toLocaleString()],
    ['Status', incident.resolved_at ? 'Resolved' : 'Active Critical'],
    ['Duration', incident.resolved_at ? `${Math.round((new Date(incident.resolved_at) - new Date(incident.started_at)) / 60000)} minutes` : 'Ongoing']
  ];
  
  doc.autoTable({
    startY: y,
    head: [['Field', 'Deatils']],
    body: overviewData,
    theme: 'grid',
    headStyles: { fillColor: [8, 8, 10] },
  });
  
  y = doc.lastAutoTable.finalY + 20;
  
  // Regional Latency at Time of Failure
  doc.setFontSize(16);
  doc.text('Network Intelligence Snapshot', 20, y);
  y += 10;
  
  const latencyData = [
    ['Mumbai Node', '42ms', 'Healthy'],
    ['Singapore Node', '68ms', 'Healthy'],
    ['US East Node', '124ms', 'Network Jitter Detected'],
    ['Frankfurt Node', '280ms', 'High Latency Anomaly']
  ];
  
  doc.autoTable({
    startY: y,
    head: [['Monitoring Node', 'Latency', 'Signature']],
    body: latencyData,
    theme: 'striped',
    headStyles: { fillColor: [0, 240, 154], textColor: [0, 0, 0] },
  });
  
  y = doc.lastAutoTable.finalY + 20;
  
  // AI Remediation Section
  if (remediation) {
    doc.setFillColor(248, 250, 252);
    doc.rect(15, y - 5, 180, 80, 'F');
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('✨ AI Smart Remediation', 20, y + 5);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Root Cause Analysis:', 20, y + 15);
    doc.setTextColor(100, 116, 139);
    const splitAnalysis = doc.splitTextToSize(remediation.analysis, 170);
    doc.text(splitAnalysis, 20, y + 22);
    
    y += 35;
    doc.setTextColor(0, 0, 0);
    doc.text('Recovery Script:', 20, y);
    doc.setFont('courier', 'normal');
    doc.setFillColor(0, 0, 0);
    doc.rect(20, y + 3, 170, 30, 'F');
    doc.setTextColor(0, 240, 154);
    doc.text(remediation.script, 25, y + 12);
  }
  
  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.text(`Generated by UpGuard AI Engine on ${new Date().toLocaleString()} - Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
  }
  
  doc.save(`UpGuard-Incident-${incident.id.slice(-8)}.pdf`);
};
